### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by luciust** [silvervest/simms#1]
So, what is the status - assuming this is 8/9bit 1MB/256kB design? I need 1MB no parity - do I need two 1Mx4 bit chips? Solder blob on 1M?

**Comment by silvervest** [comment]
Hey! Sorry, I didn't really intend on this getting out more than just who I shared it with :)

Yes, 1MB no parity SIMMs will need 2x 1MBx4 chips and put a blob on 1M side, and a blob on either EDO or FPM depending on the ICs you use and what they support. I'll get around to writing a README one of these days!

**Comment by luciust** [comment]
Cool thanks, I was looking for a tested project that would allow me to upgrade RAM in Atari STE - it needs just that - 1MB no-parity RAM. Ordering PCBs then!

EDIT: Ordered ETA early 2025 ;)
