### ISSUE TITLE
Missing link - 18/CA9 to 1MB

### ISSUE THREAD

**Issue by luciust** [silvervest/simms#2]
Hey, it seems that this is not connected on the PCB: 

![image](https://github.com/user-attachments/assets/99da59d5-60ea-4e66-aa78-e5e1cafc633f)

So far just this one seems to be off, measuring it again. Made a patch :)

PS: Yeah I'm still on it!

**Comment by silvervest** [comment]
Dang, good eye! That and the floating A9 line above it are leftovers from when I added the 1MB support but never clearly quite got there :)

Fixed in f8fbd1824436777fc3a2bb8cec8fb44150972ab2
